# Generated by Django 3.0.7 on 2024-05-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format : required , max-100', max_length=100, verbose_name='Category Name ')),
                ('description', models.TextField(blank=True, help_text='format : required ', null=True, verbose_name='Category Description ')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoryies',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format : required , max-100', max_length=100, verbose_name='Server Name ')),
                ('description', models.TextField(blank=True, help_text='format : required ', null=True, verbose_name='Server Description ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_servers', to='server.Category')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.CreateModel(
            name='Chnnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format : required , max-100', max_length=100, verbose_name='Channel Name ')),
                ('topic', models.CharField(help_text='format : required , max-100', max_length=100, verbose_name='Channel Topic ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Channel_owner', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='server.Server')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
    ]
