# Generated by Django 3.0.7 on 2026-08-02 01:50

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chnnel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_banner_upload_path),
        ),
        migrations.AddField(
            model_name='chnnel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_icon_upload_path),
        ),
    ]
